# Generated by Django 4.2.7 on 2023-11-27 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('libre_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libreauthors',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libreauthors',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
