# Generated by Django 4.2.7 on 2023-11-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('libre_authors', '0002_libreauthors_time_create_libreauthors_time_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libreauthors',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='libreauthors',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='libreauthors',
            index=models.Index(fields=['-time_create'], name='libre_autho_time_cr_f150f1_idx'),
        ),
    ]
