# Generated by Django 4.2.7 on 2023-11-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('libre_authors', '0004_alter_libreauthors_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='libreauthors',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
