# Generated by Django 4.2.7 on 2023-12-02 17:16

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ('libre_authors', '0005_libreauthors_is_published'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='libreauthors',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='libreauthors',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'DRAFT'), (1, 'PUBLISHED')], default=0),
        ),
    ]
